# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 22, 16, 29, 32, 47526)),
        ),
    ]
